lua/spectre/search/rg.lua
On Windows this command will find nothing:
```bash
rg --color=never --no-heading --with-filename --line-number --column -g '' --ignore-case -- nvim
```
Option `-g` should be removed if not path present. Will not hurt on Linux either.
References #5.
But there also another issue with plenary: https://github.com/nvim-lua/plenary.nvim/issues/146.
=> Check glob path

README.md, lua/spectre/config.lua, lua/spectre/search/ag.lua
I added config for `ag` the silver searcher. I specifically want this because ripgrep's `-g` glob flag that you use for paths disables all other ignore logic, including gitignore. `ag`'s `-G` flag does  not.
=> feat(search):  Add the 'ag' engine.

lua/spectre/search/ag.lua, lua/spectre/search/base.lua, lua/spectre/search/rg.lua, tests/search/rg_spec.lua
This implements support for supplying multiple paths separated by whitespace. I made it respect `\` as an escape character on unix and caret `^` on windows, so if you need to supply a path with a space, you can do:
```
Unix:
some/path\ with/space
Windows:
some\path^ with\space
```
=> feat: Implement support for supplying multiple paths.

lua/spectre/ui.lua
I found it took me a while to notice the Mapping(?) command prompt. There is not much in the readme and I could not figure out how to actually write the changes at first. This change should make it more obvious how to get help on mappings while still keeping the header concise.
=> Make it more clear how to get help on the mappings

README.md
Not sure if this was intentional but using the default config was throwing error because the comma was misplaced.
This was the error to be precise:
<code>
'}' expected (to close '{' at line 67) near 'is_insert_mode
'
</code>
=> Minor comma misplaced in default config

lua/spectre/init.lua, lua/spectre/ui.lua
Three problems with help menu (keybindings) in Neovim 0.8:
1. Incorect render borders
2. Error on close - `Error detected while processing CursorMoved Autocommands for "<buffer=35>": E5108: Error executing lua [string ":lua"]:1: attempt to call field '_close_preview_window' (a nil value)`
3. Error when toggle search hidden - `E5108: Error executing lua ...m/site/pack/packer/opt/nvim-spectre/lua/spectre/init.lua:549: attempt to get length of field 'search_query' (a nil value)` - when search field empty
Changes in thes pull request:
1. Remove border
2. Use `vim.api.nvim_win_close` to close popup
3. Use pcall to prevent E5108
=> Fix preview and close Help menu

lua/spectre/config.lua, lua/spectre/init.lua
Ripgrep is unable to find files/paths using the default path separator for Windows `\`.
Therefore replace the default separator with `/` so that path doesn't have to be edited manually when using `open_file_search`.
Also added a check of `sed` on Windows in `config.lua`
=> fix: use correct path separator for windows in open_file_search

lua/spectre/init.lua, plugin/spectre.lua
It adds the `:Spectre` command not just when the buffer local mappings are created, but when vim plugin scripts are loaded i.e. you start out with being able to execute `:Spectre`.
=> feat: add `:Spectre` command with vim plugin script

lua/spectre/init.lua
This adds the mapping description to the actual keymap. This is useful when browsing the keymaps or using plugins such as `which-key`
=> feat: add mapping description to keymap

lua/spectre/actions.lua
This patches fix https://github.com/nvim-pack/nvim-spectre/issues/106
It turns out the problem unrelated to the `nvim_win_set_cursor` but rather reference file in the search list buffer doesn't exists in the path, then it will open new empty buffer (just like creating new file buffer). Thus, it will expected that the reference cursor (col, row) doesn't exists in the new empty buffer.
With this patch, we just fill out `state.cwd` if its empty or nil (not exists) using current working directory (by `vim.fn.getcwd()` function). Thus, it will always refer to fullpath of referenced file.
=> fix: use full path for filename

lua/spectre/config.lua, lua/spectre/ui.lua
Give user the option to change the highlight group for the header text
=> feat: Add user highlight config for headers

lua/spectre/init.lua
BufUnload was not firing the `on_close()` handler, which prevented the last search query from being saved.  This change uses the `BugLeave` event instead and prints a message to the mini buffer when no previous search criteria exists.
=> Fix resume last search

lua/spectre/init.lua
This commit exposes the method M.toggle() which can be used like
``` lua
lua require("spectre").toggle()
```
Providing an intuitive way to open/close spectre with a single mapping. 
https://www.youtube.com/watch?v=Ik7Yovd_ZKU
Closes #142
=> feat(spectre-toggle)

lua/spectre/init.lua
require("spectre").close() doesn't work fine when mixed with toggle. This PR fixes it. Related to #148
```lua
M.toggle = function(opts)
if state.bufnr ~= nil then M.close()
else M.open(opts) end
end
M.close = function()
if state.bufnr ~= nil then
local wins = vim.fn.win_findbuf(state.bufnr)
for _, win_id in pairs(wins) do
vim.api.nvim_win_close(win_id, true);
end
state.bufnr = nil -- By having this line here instead of in toggle, we ensure the state is always cleared once the buffer cease existing.
end
end
```
=> fix(close) state.bufnr is now cleared when the spectre buffer is closed.

README.md, lua/spectre/init.lua, lua/spectre/state.lua
Fixes #150 
This PR fixes the state tracking of `M.toggle()` by using a dedicated state instead of re-using state.bufnr.
I also implemented the right autocmd to ensure the state is consistent no matter what command the user uses to close the spectre window (:bd, :bw, :close... anything goes).
So this should fix any possible issue related with toggle.
=> fix(M.toggle) Dedicated state instead of re-using state.bufnr

lua/spectre/init.lua, lua/spectre/ui.lua
I added a `begin_line_num` in `M.open`'s opts.
Every time I open the spectre with the givin word, the cursor position always in search placeholder, makes me need to move down multi lines to scan the result
Having this option, I set the keymap below, it feels so good
=> feat: opts: begin_line_num

lua/spectre/actions.lua, lua/spectre/replace/base.lua, lua/spectre/replace/sed.lua
Currently, the errors from Sed aren't printed anywhere, which makes it hard to troubleshoot them. This commit prints the command, args, and stderr to help with that.
=> Print errors from Sed replace command

.github/workflows/release.yml
This PR is part of a push to get (neo)vim plugins on [LuaRocks](https://luarocks.org/labels/neovim).
* See [this blog post](https://mrcjkb.github.io/posts/2023-01-10-luarocks-tag-release.html), which follows up on [a series of posts](https://teto.github.io/posts/2021-09-17-neovim-plugin-luarocks.html) by @teto.
* Add a workflow that publishes tags to LuaRocks when a tag is pushed.
* Tagged releases are installed locally and then published to LuaRocks.org.
On PRs, a test release is installed, but not published.
* For the release workflow to work, someone with a LuaRocks.org account will have to add their [API key](https://luarocks.org/settings/api-keys) to this repo's [GitHub actions secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for …
=> ci: package the plugin for lua(rocks)

build.sh
Build issues such as https://github.com/nvim-pack/nvim-spectre/issues/185 are not reflected in the exit status so it silently fails when building. Updating this to fail allows plugin managers like lazy.nvim to identify the failed build
=> Update build.sh to fail if build fails

README.md, doc/spectre.txt, lua/spectre/config.lua, lua/spectre/init.lua, lua/spectre/ui.lua
Hi, this plugin is so wonderful and I use it everyday. And I found an bug (if we can call it a bug) for the line number, the pull request is used to fix it.
During the search, if there are more than one result found in the same file, we can only see the the line/column numbers of the first matched result showing behand the filename. 
Here is an examle:
I think it is useless, because we still can't know the line number of each matched result.
The following formats is more useful. we can see which file the results belong to, and we can also know the line number of each result. 
This pull request is used to show the new formats, please help to check it.
=> show line number for each result text

spectre_oxi/.cargo/config.toml
nvim-oxi has [those exact flags](https://github.com/noib3/nvim-oxi/blob/c9a71b0e5c4edc4f0916a5d0fb20d73bce0c52ef/.cargo/config.toml), I'm adding those here to support NixOS on darwin (see https://github.com/NixOS/nixpkgs/pull/314639).
=> build: add apple-darwin rustflags

README.md, lua/spectre/actions.lua, lua/spectre/config.lua
This PR adds trouble.nvim integration to send entries to trouble.nvim quickfix list.
- Added use_trouble_qf flag to the config table
- Updated send_to_qf action logic
- Updated README
Closes #238
=> feat: added trouble.nvim integration

doc/spectre.txt, lua/spectre/config.lua, lua/spectre/init.lua
I'm on macOS and, although the `sed` on my path is GNU sed, I still see the "You need to install gnu sed 'brew install gnu-sed'" warning. This is because the plugin assumes macOS users will be using the Homebrew package manager and thus checks for the `gsed` executable. While this is a safe assumption for many (most?) macOS users, folks who are using other package managers, have aliased `sed` to `gsed`, etc. will see false positives.
I worked around this in a rather simple way, by adding a `warn` option that the user can simply set to false if they know better than the plugin. From the doc update:
> Warnings are emitted based on your operating system and chosen executables. If you find one of these warnings to be in error, you may silence it by setting the respective `warn` key. For …
=> feat: config to silence executable warnings

plugin/spectre.lua
Hello
Currently the file `plugin/spectre.lua` execution takes just over 12.2ms on my laptop. I found it surprising giving that it only sets a single command. Making this small adjustment the execution time drops to 0.28ms. While 12ms is not a big difference this file is being sourced automatically at start up and it would be preferred to not block the startup by default when possible.
Hope this helps and thanks for your work
=> feat: lazy load spectre core for the command

lua/spectre/init.lua
use sed if available in darwin, useful for darwin-nix users where `gnused` is installed as `sed`
=> fix(sed): detect sed on darwin

README.md, doc/spectre.txt, lua/spectre/init.lua
Not sure if this change is desirable, but I found it useful to open Spectre in a floating window in my own config.
Feel free to close this if you think it is a bad change.
=> feat: allow open_cmd to be a lua function

lua/spectre/highlight.lua
param `default = true` will be honored to user's pre-define highlight groups, which will be friendly for pre-defined colorshemes.
=> feat add default to highlight group definition.

lua/spectre/config.lua, lua/spectre/replace/sed.lua
Fixes the issue of in-place replacement on macOS by not creating files ending with mistakenly accepting `-E` arg as part of `-i -E` as macOS sed requires an empty pair of quotes like so `-i "" -E`  (related issue #259 ):
FIx removes default args in `config.lua` and updates `sed` args to be determined by `Darwin` (macOS) vs others.
=> updates sed in-place args to support macOS

build.sh
`/bin/bash` doesn't exist in some niche Linux OSs like Guix or NixOS, but `/bin/sh` does. This PR updates the build script to use POSIX shell syntax by replacing `==` with `=`. I also added `-f` flag for all cp commands, so the script can be invoked without fail.
=> Use POSIX shell for build.sh script
